config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	resources :videos
	resources :users
    resources :countries 
    root 'videos#index'

    get 'video', to: "videos#video"
    get 'search', to: "videos#search"
    get 'login', to: "users#login"
    post 'login', to: "users#login"
    get 'logout', to: "users#logout"
    post 'new_view/:id', to: "videos#new_view"
    post '/new_comment', to: "videos#new_comment"
    post '/new_like', to: "videos#new_like"
    get 'add_flag', to: "videos#add_flag"
    post 'add_flag', to: "videos#post_flag"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :video


end

app/models/country.rb
class Country < ApplicationRecord
	has_attached_file :flag,
	 :styles => {

		medium: "320x200>",
		small: "45x30>",
		large: "800x500>",
		thumb: "150x90!"

	}

	validates_attachment_content_type :flag, content_type: /\Aimage\/.*\Z/

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user 
	belongs_to :video
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :videos
	has_many :comments
	has_many :likes

	has_attached_file :image,
	 :styles => {

		medium: "320x200>",
		small: "250x220>",
		large: "800x500>",
		thumb: "150x90!"

	},
 	 :default_url => "../../missing.png"
 	validates :email, presence: true	

	validates :password, presence: true	
	validates :name, presence: true	

	validates :password_confirmation, presence: false	
    validates :email, uniqueness: true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates :password, length: { minimum: 6 }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	

	def valid_attribute?(attribute_name)
  		self.valid?
  		self.errors[attribute_name].blank?
	end


end

app/models/video.rb
class Video < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_many :likes

	has_attached_file :video,
	    processors: lambda { |a| a.is_video? ? [ :ffmpeg ] : [ :thumbnail ] }

	validates_attachment_content_type :video, content_type: /\Avideo\/.*\Z/

	has_attached_file :thumbnail, styles: {

		medium: "320x200>",
		small: "250x220>",
		large: "800x500>",
		thumb: "150x90!"

	}

	validates_attachment_content_type :thumbnail, content_type: /\image\/.*\Z/

	validates :title, presence: true	
	validates :country, presence: true	
	validates :city, presence: true	
	validates :video, presence: true
	validates :description, presence: true
	
	validates :thumbnail, presence: true



	def self.search(search)
	  if search
			where("title LIKE ?", "%#{search}%")
	  else
	  	Video.all
	  end
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new 

	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show 
		@user = User.find(params[:id])
		@boi = User.find(params[:id])
	end

	def new 
		@user = User.new 
	end

	def create 
		@user = User.new(user_params) 
		if @user.save
			session[:user] = @user.id
			redirect_to "/users/#{@user.id}"
		else 
			flash[:error] = "#{@user.errors.details}  "
			render action: :new 
		end 
	end 

	def edit 

		@user = User.find_by_id(params[:id])

		if params[:id].to_i == session[:user].to_i
			@user = User.find_by_id(params[:id])
		else 
			redirect_to "/videos"
		end 
	end 	

	def update 
		
		@user = User.find(params[:id])
		email = params[:user][:email]
		name = params[:user][:name]
		image = params[:user][:image]
		message = []
	

		if @user.email != email 	
			@user.email = email 
			if @user.valid_attribute?(:email)  

				@user.update_attribute(:email,email)
				message.push ("E-mail successfully updated")	
			else 
				message.push("E-mail is invalid")
				flash[:error] = @user.errors[:email]
				render action: :edit
				return

			end 
		end 

	if @user.name != name 	
			@user.name = name 
			if @user.valid_attribute?(:name)  

				@user.update_attribute(:name,name)
				message.push ("Name successfully updated")	
			else 
				message.push("Name is invalid")
				flash[:error] = @user.errors[:name]
				render action: :edit
				return

			end 

	end

		if @user.image != image 
			if @user.valid_attribute?(:image)  
				@user.update_attribute(:image, params[:user][:image])
				@image = image 
			else 
				flash[:error] = @user.errorss[:image]
				message.push("Image is invalid")
				render action: :edit
				return

			end 
		end 

		redirect_to "/users/"+@user.id.to_s






	end


	def logout 
		session[:user] = nil 
		redirect_to "/videos"

	end 

	def login
		@user = User.new  
		@error = false 
		if params.key?("email") and params.key?("password")
			@user = User.find_by(email: params[:email])
			if @user and @user.authenticate( params[:password])
				session[:user] = @user.id
			 redirect_to "/users/#{@user.id}"
			else 
				@user = User.new  
				@user.email = params[:email]
				@error = true 
				render action: :login
			end 	
		end 	
	end 

	private 

	def user_params
		params.require(:user).permit(:name,:email,:password,:image)

	end
end

app/controllers/videos_controller.rb
	class VideosController < ApplicationController
	before_filter :get_user, :only => [:new,:create]
	skip_before_filter :verify_authenticity_token , :only => [:new_view,:new_comment,:new_like,:create]

	def index 
		@videos = Video.all

	end

	def video 
		@video = Video.all.last 
	end

	def show 
		@video = Video.find(params[:id])
		@videos	 = Video.all 	
		@comments = @video.comments 
		@liked = false 
		if not session[:user] == nil 
		 @user = User.find(session[:user])
		 @liked =  @video.likes.where(user_id: @user.id).first	 != nil 
		else 
			@user = nil 
		end 

	end 

	def new_like 

		video_id = params[:video_id]
		user_id = params[:user_id]

		like = Like.where(user_id: user_id, video_id: video_id).first	
		if like != nil 
			like.destroy()
			redirect_to "/videos/"+video_id.to_s
		else 
			like = Like.new 	
			like.video_id = video_id
			like.user_id = user_id
			
			if like.save 
				redirect_to "/videos/"+like.video_id.to_s
			end 
		end 
	end 

	def new_view 
		video =  Video.find(params[:id])
		video.update_attribute(:views, video.views+1)

	end 

	def new_comment 
		comment = Comment.new 
		comment.video_id = params[:video_id]
		comment.user_id = params[:user_id]
		comment.comment = params[:comment]

		if comment.save 
			redirect_to "/videos/"+comment.video_id.to_s
		end 

	end 

	def search 
		@query = params[:query]
		@videos = Video.search(@query)
		@pages = (@videos.count / 9.to_f).ceil

		@page = params[:page].to_i()	

		@start_index = 9 * (@page-1) 
		@end_index = @start_index + 8

		if @start_index > @videos.count
			@start_index = 0
			@end_index = 8 
		end
		
		if @end_index > @videos.count - 1
			 @end_index = @videos.count - 1 
		end

	end

	def add_flag 
		@country = Country.new 
	end 

	def post_flag
		@country = Country.new(country_params)
		if @country.save
			redirect_to "/videos"
		else 
			render action: :add_flag 
		end 
	end 

	def new 
		@messages = []
		@countries = Country.all
		@video = Video.new 
	end 

	def create 
		@video = @user.videos.new(video_params)
		if @video.save
			redirect_to "/videos"
		else 

			@messages = @video.errors 
			render action: :new 
		end 
	end 

end

private 

def video_params 
	params.require(:video).permit(:title,:video,:thumbnail,:city,:country,:description)
end 

def country_params 
	params.require(:country).permit(:name,:flag)
end

def get_user 
	if not session[:user] 
		redirect_to "/users/new"
	else 
		@user = User.find(session[:user])

	end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  
    <%= yield %>

  </body>
</html>

app/views/users/edit.html.erb
<%= javascript_include_tag "croppie/croppie.js", "data-turbolinks-track" => "reload" %>
<%= javascript_include_tag "edit_user.js" %>
<%= stylesheet_link_tag "edit_user.css", media: "all" %>
<%= stylesheet_link_tag "croppie/croppie.css", media: "all" %>

<%=  render "videos/nav" %>

<div class="background"> 
	<%= form_for @user, html: {  id: "form", class: "form" ,multipart: true } do |f|  %> 


	  <div class="pic"> 
	  <img id = "orig" src="<%= @user.image.url %>" class="profile-pic"/>

		<img id="img"  src="<%= @user.image.url %>" class="profile-pic"  />
	  </div>
	  	<div class="buttons"> 
	  		<span class="pic-button" onclick="flip(-1)">  -90 </span>
	  		<span class="confirm-button" onclick="confirmImage()"> Confirm</span> 
		  	<span class="pic-button" onclick="flip(1)">  +90 </span>

	  	</div>

	  <div class="fields" >

	  	<h4> Update Profile Pic </h4>
 	  
			<input type="hidden" name="user[image]" id="pic" /> 
			<input type="file" onchange='handleChange(event)'>


 	  	<br /> 
 	  	<div class='yo'> 
	 	  	<% if defined? @image %> 
	 	  		<%= @image.inspect %> 
	 	  	<% end %> 
	 	  </div>



	  	<%= f.label :name, class: "label"%> 
	 	<%= f.text_field :name , :placeholder =>' User Name',:value => @user.name,class: "form-control form-control-lg  field" %>
	  	 <%= f.label :email, class: "label" %> 

		  <%= f.text_field :email ,:value => @user.email,   :placeholder =>' Email',class: "form-control form-control-lg field " %>
		  

	 	  <button onclick="submitform()" class=" submit-button btn btn-info"> Update Profile </button> 

	 	</div>  


	<% end %>
</div>

app/views/users/login.html.erb
  
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>
<%= stylesheet_link_tag "login", media: "all" %>


<div class="background"> 

	<%= form_tag login_path, :class => "form"  do   %> 
		
		<% if @error %> 
			<span class="error-text"> Username or Password provided Incorrect </span> 
		<% end %> 
			<%= link_to "HappyTravlr",videos_path, class: "logo" %>  

		<div class="fields" > 

		<%= text_field_tag "email" ,@user.email,class: "form-control form-control-lg field ",placeholder: 'Username or Email'
		   %>	
		<%= password_field_tag "password" ,nil,class: "form-control form-control-lg field ",placeholder: 'Password'
		   %>
		 
 	   <%= submit_tag nil, class: "btn btn-primary" %>

	 	</div>  

	 	<%= link_to "Register", new_user_path, class: "register-text" %> 

	<% end %>
</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>
<%= stylesheet_link_tag "new_user", media: "all" %>
<div class="background">
		 




	<%= form_for @user, html: {  class: "form" ,multipart: true } do |f|  %> 
	<%= link_to "HappyTravlr",videos_path, class: "logo" %>  

<% if @user.errors.count > 0 %> 
			<% @user.errors.each do |type,message|  %> 
				<div class="error"> <%= type.capitalize %> <%= message %> 	</div> 
			<% end%> 
<% end %>

	  <div class="fields" > 
	 	 <%= f.text_field :name ,   :placeholder =>' User Name',class: "form-control form-control-lg	 field" %>

		  <%= f.text_field :email ,   :placeholder =>' Email',class: "form-control form-control-lg field " %>

			<%= f.password_field :password ,   :placeholder =>'Password',class: "form-control form-control-lg field" %>
	 	   <%= f.submit "Register ",class: "btn btn-primary" %>

	 	</div>  

	 		 	<%= link_to "Login", login_path, class: "login-text" %> 



	<% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>
<%= stylesheet_link_tag "profile", media: "all" %>
<%= stylesheet_link_tag "nav", media: "all" %>
<%=  render "videos/nav" %>

<style type="text/css">
	.profile-pic{
	
	background-image:url("<%= @user.image.url %>");


}


</style>


<body>

	<div id="profile-info">
		<% if not @user.id == session[:user] %> 
			<span class="user-name"> Tomi Okiji </span>	
		<% else %> 
			<%= link_to "Change Profile Pic", edit_user_path(@user), class: "change-pic" %> 
		<% end %> 
		 

		<div class="profile-pic"> </div>
		<div id="r" >


			 <div id="holder">
			
				
				<% if @user.videos.count > 0 %> 
					<span class="video-filter-text">Recent Uploads </span>
				<% else %> 
					<span class="video-filter-text"> No Recent Uploads </span>
				<% end %> 
					<div class="video-container"> 
					<% i = 0 %> 
					<% @user.videos.each do |video| %> 
					<%= link_to(video_path(video) }) do %> 
							  	<span class="video-title"><%= video.title %> </span>
							  	<span class="place"> <%= video.city+","+video.country %> </span>
					<% end %> 

						  	<% if (i+1) % 3 == 0  %> 
									<div class="line-break" ></div>
								<% end %> 
								<% i+=1 %> 

						<% end %> 

					</div>

				</div>
		</div>
	</div>
    	<%=  render "videos/footer" %>

</body>

	

app/views/videos/_footer.html.erb
<div style="display: flex; 
	flex-direction: row; 
	justify-content: space-between;
	padding-left: 100px; 
	padding-right: 100px; 
	padding-top: 15px; 
	background-color: black; 
	width: 100%; 
	color:lightgrey;
	height:50px;">
	<span>Copyright © 2017 HappyTravlr </span>
	<span> tomiokiji@gmail.com </span>
</div>

app/views/videos/_nav.html.erb
<% if session[:user] %> 
	<% style =  "background-image:url("+User.find(session[:user]).image.url+");" %> 	
<% end %>
<style> 

.dropbtn {

	<%= style %> 
	background-position: center;
	background-size: cover;
    width:40px;
    height:40px;
    margin-top:5px;
    margin-left:20%;
    border-radius: 50%; 
    border: none;
    cursor: pointer;
}
</style>

<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>

<%= stylesheet_link_tag "nav", media: "all" %>
	
	<div class="main">
		<%= link_to "HappyTravlr", videos_path,class: "logo" %>
		<ul class="nav"> 
			<li class="top-nav">
				<div class="search-bar-holder form-group">
					<div class="input-group ">
	   				<input type="text" id="search"  class=" search-bar form-control" placeholder="Search a destination">
	    			<span class=" search-bar input-group-btn">
		      		<button class=" search-bar btn btn-default" onclick="search()">
		    				<i class="  glyphicon glyphicon-search"></i> 
		    			</button>
	    			</span>
					</div>
				</div>
			</li>	 
				<% if not session[:user] %> 
					<li class="first-link"> <%= link_to "Login", login_path %> </li>
					<li> <%= link_to "Register", new_user_path %> </li>
				<% else %> 
					<li class="first-link"> <%= link_to "Upload", new_video_path %> </li>
					<li > 
						<div class="dropdown">
						  <div onclick="myFunction()" class="dropbtn"></div>
						  <div id="myDropdown" class="dropdown-content">
						   <%= link_to "Profile", user_path(session[:user]) %> 
							 <%= link_to "Logout", logout_path %> 
						  </div>
						</div>
					</li>

				<% end %>  


			</ul>

	</div> 

<script>
	/* When the user clicks on the button, 
	toggle between hiding and showing the dropdown content */
	function myFunction() {
	    document.getElementById("myDropdown").classList.toggle("show");
	}


	function search(){
		var search = $("#search").val(); 
		window.location.replace("/search?query="+search+"&page=1");


	}

	$("#search").keyup(function(event)
	{
	    if(event.keyCode == 13)
	    {
	    	search(); 
	    }
	

	});

	// Close the dropdown if the user clicks outside of it
	window.onclick = function(event) {
	  if (!event.target.matches('.dropbtn')) {

	    var dropdowns = document.getElementsByClassName("dropdown-content");
	    var i;
	    for (i = 0; i < dropdowns.length; i++) {
	      var openDropdown = dropdowns[i];
	      if (openDropdown.classList.contains('show')) {
	        openDropdown.classList.remove('show');
	      }
	    }
	  }
}
</script>

app/views/videos/add_flag.html.erb
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>

<%=  render "nav" %>



<%= form_for  @country,  :url => url_for(:controller => 'videos', :action => 'post_flag'), html: {   multipart: true } do |f| %>
	

	<%= f.text_field :name ,:placeholder =>' Name',class: "form-control title" %>
	 
<%= f.file_field :flags %> 
	<%= f.submit %> 


<% end %>

app/views/videos/index.html.erb
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>
<%= stylesheet_link_tag "index" %>
<%= javascript_include_tag "index.js" %>

<html>

	<body> 
	<div class="background"> 
		<header class="main">

			<ul class="nav"> 
					<% if not session[:user] %> 
						<li> <%= link_to "Login", login_path %> </li>
						<li> <%= link_to "Register", new_user_path %> </li>
					<% else %> 
						<li> <%= link_to "Upload", new_video_path %> </li>

						<li> <%= link_to "Logout", logout_path %> </li>
					<% end %> 
			</ul>
		</header> 


 	<p class="slogan-holder" >
 			<span class="logo"> HappyTravlr </span>

 		<br> 

		<span class="top">A Video Site for Travelers by Travelers </span>
		<br /> 
	 	<span class="bottom">Travel, Shoot, Share </span>
	</p> 


	
	  <div style="width:50%;" class="form-group has-feedback">
	    <input type="text" id="search" class="input-lg search-bar form-control" placeholder="Search Dubai" />
	    <i style="color:grey;font-size:30px; 		margin-top:10px;" 
	    class="form-control-feedback glyphicon glyphicon-search"></i>
	  </div>

  </div>

  <div> 

  </div>

  <div> 



  <div id="e">
  	<h1 class="discover"> Exlore Trending Travel Videos </h1>
  	<span class="discover-under"> Watch some of the video's that have 
  														been handpicked by the HappyTravlr community</span> 
 		<div class="video-container"> 
 		<% if @videos.count > 0 %> 
	 		<% i = 1 %> 
			<% @videos.reverse_each do |video| %> 
				<a href="/videos/<%=video.id %>" class="video"
					style="background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('<%= video.thumbnail.url(:large) %>');

							background-position: center; 	
							background-repeat: no-repeat; 
							background-size: cover;



					"
				 >
					<span class="video-title"> <%= video.title %> </span>
					<span class="place"> <%= video.city %>,<%= video.country%> </span>
					<span href="#" class="video-by"><%= video.user.name %> </span`	>

				</a>

				<% if (i+1) % 3 == 0  %> 
					<div class="line-break" ></div>
				<% end %> 
				<% i+=1 %> 

			<% end %>
		<% end %> 
		</div>

	</div>

	<div class="bottom-join"> 
		<h1> Join HappyTravlr !</h1>
		<span> Get your video put on the front page </span>
		 <%= link_to "Register", new_user_path ,class: "sign-up-link" %>
	</div>

 
    	<%=  render "videos/footer" %>

</body> 


</html>  	

app/views/videos/profile.html.erb
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>
<%= stylesheet_link_tag "profile", media: "all" %>
<%= stylesheet_link_tag "nav", media: "all" %>
<%=  render "nav" %>

<body>

	<div id="profile-info">
		<span class="user-name"> Tomi Okiji </span>	
		<div class="profile-pic"> </div>
		<span class="places-text"> Countries's I've been to  </span> 
		<div id="r" >


			 <div id="holder">
				<div className="flags-container"> 


					<img class="flag-img" src="	<%=asset_path 'uk.png' %>" />
					<img class="flag-img" src="	<%=asset_path 'france.png' %>" />
					<img class="flag-img" src="	<%=asset_path 'germany.png' %>" />
					<img class="flag-img" src="	<%=asset_path 'uk.png' %>" />

					
				</div> 

				<span class="video-filter-text">Recent Uploads </span>
					<div class="video-container"> 

					<% for i in 0..6%> 
							<a href="video" class="video" >
						  		<span class="video-title"> First Time in London</span>
						  		<span class="place"> London,Uk</span>
						  	</a>
					<% end %> 
					</div>

				</div>
		</div>
	</div>
</body>

	

app/views/videos/search.html.erb
<%= stylesheet_link_tag "search", media: "all" %>
<%=  render "videos/nav" %>



<body> 	

	<div class="search-results-text"> 
		<% if @videos.count > 0 %> 
			Search Results for "<%= @query %>"
		<% else %> 
			There were not videos found for "<%= @query %>"
		<% end %> 
	</div>

<br />
	
	<div class="search-results">
	
 
		<% for i in @start_index .. @end_index  %> 
			<% video = @videos[i] %> 
			<div class="result">
				<%= link_to "", video_path(video), class: "video", style: 
					'background-image: url('+ video.thumbnail.url(:medium) + ');'

				  %>
				<div class="video-info"> 
					<%= link_to user_path(video.user.id), class: "video-by" do %>
					<% style ="background-image: url("+ video.thumbnail.url(:medium) +") " 
					%> 

							<div class="video-title"> <%= video.title %> </div>
							<div class="video-location"><%= video.city %>,<%= video.country %> </div> 
					<span class="profile" style='<%= style %>' > </span> 
						 <%= video.user.name %> |
						<span class="view-count"> <%= video.views %> views</span>
					<% end %> 
				</div>
			</div>
		<% end %> 
		<div class='line-break'></div>
		<div class="pages">
		<% if @page > 1 %> 	
			<%= link_to "Previous", "/search?query="+@query+"&page="+(@page-1).to_s, class: "page" %> 
		<% end %> 
		<% for i in @page .. @pages %>
		 	<% if @page == i %> 
		 		<% styles = "active page" %> 
		 	<% else %> 
		 		<% styles = "page " %> 
		 	<% end %> 

			<%= link_to i, "/search?query="+@query+"&page="+(@page+i - 1).to_s, class: styles %> 

		<% end %> 

		<% if @page < @pages %> 	
		<%= link_to "Next", "/search?query="+@query+"&page="+(@page + 1).to_s, 
								 class: "page" %> 
		<% end %> 

	</div>	

	</div>



</body>

app/views/videos/show.html.erb
	
<%= stylesheet_link_tag "bootstrap/css/bootstrap", media: "all" %>
<%=  render "nav" %>
<%= stylesheet_link_tag "video", media: "all" %>
<%= stylesheet_link_tag "show_video", media: "all" %>
<%= javascript_include_tag "http://vjs.zencdn.net/5.12.6/video.js" %>
<%= javascript_include_tag "show_video.js" %>


<body> 
	

		<video id="my_video" class=" vjs-big-play-centered video-js vjs-tech" controls 				
				preload="auto" 

			  poster="<%= @video.thumbnail.url(:large)  %>"

			   data-setup="{}">
		    <source src="<%= @video.video.url %>" type='video/mp4'>
		   	<source src="<%= @video.video.url %>" type='video/mov'>

		    <p class="vjs-no-js">
		      To view this video please enable JavaScript, and consider upgrading to a web browser that
		      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
		    </p>
		</video>

	
	 <div class="under-video">
			<div class="video-info-holder"> 
				  <div class="video-info"> 
					 <span class="video-title"><%= @video.title %> </span>
					 <p class="from ">by 
					 	<span class="by"> <%= @video.user.name %> </span> 

						 	<%= @video.created_at.strftime("%b %d %Y") %>

					 </p>
					 <%= link_to(user_path(@video.user), html_options = {}) do %> 
					 	<div class="user-pic"> </div>
					 <% end %> 

				</div >

				 <div class="video-analytics">
					 <div class="video-icons"> 
							<div class="views" >
							 <i class="video-icon glyphicon glyphicon-play "></i> <span class="view-count-text"> <%= @video.views %> </span>
							</div>
							<div> 
								 <i id="favorite-button" class="video-icon glyphicon glyphicon-heart">
								 </i> 
								 <span class="like-count"> <%= @video.likes.count %> </span>
							 </div>
					 </div>
					 <p class="video-description">
					 		<%= @video.description %>
					  </p>
					 </div>
					 <div class="comments">
					 	<h4> Comments </h4>
					 	<% if not session[:user] == nil %> 
						 	<form id="comment-form" action="/new_comment" method="post">
						 		<input type="hidden" name="video_id" value="<%= @video.id %> " />
						 		<input type="hidden" name="user_id" value="<%= @user.id %> "/>
						 		<textarea placeholder="Post a comment " id="add_comment"  name="comment" class=" form-control"></textarea>  
						 		<button class="btn post-comment-btn btn-info">Post</button>
						 	</form>
						<% else %> 

							<%= link_to "Register and leave a comment!", new_user_path, 
							class: "leave-comment" %> 

						 <% end %> 
						
				

					 	<% @comments.each do |comment| %> 

						 	<div class="user-comment"> 

						 		 <div style="background-image: url(<%= comment.user.image.url %>);" > 
								</div>

						 		<div class="comment-image-right"> 
						 			<%= link_to comment.user.name, user_path(comment.user.id), 
						 				 class: "user-name" %> 
						 				 <span> 
						 				 	<%= comment.created_at.strftime("%b %d %Y") %>

						 				 </span>
							 		<div class="comment-text"> 
							 			<%= comment.comment %> 
							 		</div>
							 	</div>

						 	</div>
					 	<% end %> 



					 </div>
			</div>

			<div class="recommended-videos">
				<span class="more-videos-text"> 
					Recommended videos 
				</span>
				<div class="line"> </div> 		

			<% @videos.each do |video| %> 
			<% if @video.id == video.id %> 
				<% next %> 
			<% end %> 
				<%= link_to video_path(video), class: "rec-video-container" do %> 


							<div class="recommended-video" 
									style="background-image: 
												url(<%= video.thumbnail.url(:thumb)%>);"
							> </div>
							<div class="video-text-container"> 
								<span class="rec-video-title"><%= video.title %>  </span>
								<span class="rec-video-creater"> <%= video.user.name %> </span>
							</div>
					
				<% end %> 
			<% end %>
	 </div>


</body>